#!/usr/bin/env bash

# This is just a quick hack to determine if the code coverage
# is enough or not.
#
# @author Michael Haeuslmann <haeuslmann@gmail.com>

NO_COLOR='\x1b[0m'
OK_COLOR='\x1b[32;01m'
ERROR_COLOR='\x1b[31;01m'
WARN_COLOR='\x1b[33;01m'

min_cov=95
cov=`php tools/phpunit.phar --coverage-text --colors=never \
    | egrep -o  "Lines:[[:space:]]+([0-9])+" \
    | head -n1 \
    | sed 's/Lines: *//'`

if [ "$cov" -gt "$min_cov"  ]; then
    printf "${OK_COLOR}✓ Coverage is $cov%%${NO_COLOR}\n"
    exit 0
else
    printf "${ERROR_COLOR}✗ Line coverage is only $cov%%, but needs to be at least $min_cov%%${NO_COLOR}\n"
    exit 1
fi

